-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 11:23:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`odpowiedzi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`odpowiedzi` (
  `idodpowiedzi` INT NOT NULL AUTO_INCREMENT,
  `odpowiedz` VARCHAR(45) NULL,
  `pytania_idpytania` INT NOT NULL,
  PRIMARY KEY (`idodpowiedzi`, `pytania_idpytania`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`poprawna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`poprawna` (
  `idpoprawne` INT NOT NULL,
  `poprawna` VARCHAR(45) NULL,
  PRIMARY KEY (`idpoprawne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pytania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pytania` (
  `idpytania` INT NOT NULL AUTO_INCREMENT,
  `pytanie` VARCHAR(45) NULL,
  `odpowiedzi_idodpowiedzi` INT NOT NULL,
  `odpowiedzi_pytania_idpytania` INT NOT NULL,
  `poprawna_idpoprawne` INT NOT NULL,
  PRIMARY KEY (`idpytania`, `odpowiedzi_idodpowiedzi`, `odpowiedzi_pytania_idpytania`, `poprawna_idpoprawne`),
  CONSTRAINT `fk_pytania_odpowiedzi1`
    FOREIGN KEY (`odpowiedzi_idodpowiedzi` , `odpowiedzi_pytania_idpytania`)
    REFERENCES `mydb`.`odpowiedzi` (`idodpowiedzi` , `pytania_idpytania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pytania_poprawna1`
    FOREIGN KEY (`poprawna_idpoprawne`)
    REFERENCES `mydb`.`poprawna` (`idpoprawne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`uczen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`uczen` (
  `iduczen` INT NOT NULL,
  `Imię` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  PRIMARY KEY (`iduczen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `idtest` INT NOT NULL,
  `pytanie_id` VARCHAR(45) NULL,
  `odpowiedz_id` VARCHAR(45) NULL,
  `uczen_id` VARCHAR(45) NULL,
  `uczen_iduczen` INT NOT NULL,
  `pytania_idpytania` INT NOT NULL,
  PRIMARY KEY (`idtest`, `uczen_iduczen`, `pytania_idpytania`),
  CONSTRAINT `fk_test_uczen1`
    FOREIGN KEY (`uczen_iduczen`)
    REFERENCES `mydb`.`uczen` (`iduczen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_pytania1`
    FOREIGN KEY (`pytania_idpytania`)
    REFERENCES `mydb`.`pytania` (`idpytania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
